import type { AuthRow } from "../api";
import type {
  ClientLsData,
  CommandsData,
  DoctorData,
  ProfileLsData,
  ServerInfoData,
  ServerLsData,
} from "../bridge/data";
import type {
  ClientDirectAddData,
  ClientDirectLsData,
  ClientDirectRmData,
  ClientEditData,
  ClientImportData,
} from "../types/client";
import type { InspectData } from "../types/inspect";
import type { ProfileInspectData } from "../types/profile";
import type { ServerSearchData } from "../types/server";
import type { StatusDoc } from "../servers/model";
import { commandsFixture } from "./commandsRegistry";
import { CtlReplyFailure } from "./ctlReply";
import golden from "../../../src-tauri/tests/fixtures/ctl-envelopes/commands.json";

/** A registry with every case of the Servers screen: servers that are connected, one that
 * fails to start, two that answer 401, one that is not in the active profile; three profiles;
 * four clients, one of them with an orphan entry. The names are made up. Everything here has
 * the shape of the real `toolportctl --json` output (see `servers.test.ts`). */

export const ctlFailure = (code: string, message: string, data?: unknown) =>
  new CtlReplyFailure(code, message, data);

export const commandsGolden = (golden as { envelope: { data: unknown } }).envelope
  .data as CommandsData;

const attentionRow = commandsFixture.commands.find((row) => row.id === "attention ls");

/** The real registry plus the `attention ls` row the sidebar probes for; the golden is
 * generated by a build that does not have it yet. */
export const commandsServed: CommandsData =
  !attentionRow || commandsGolden.commands.some((row) => row.id === attentionRow.id)
    ? commandsGolden
    : {
        ...commandsGolden,
        commands: [...commandsGolden.commands, attentionRow],
        counts: {
          ...commandsGolden.counts,
          commands: commandsGolden.counts.commands + 1,
          rows: commandsGolden.counts.rows + 1,
        },
      };

const BASE = {
  since: 1_790_000_000,
  expiresAt: null,
  ttlSecs: null,
  lastProbe: 1_790_000_300,
};

const loginRow = (server: string, reason: string): AuthRow => ({
  ...BASE,
  server,
  state: "needs_reauth",
  reason,
  fix: {
    action: "reauth",
    server,
    label: `Sign in to ${server} again`,
    command: `toolportctl auth login ${server}`,
    ipc: null,
  },
});

const okRow = (server: string): AuthRow => ({
  ...BASE,
  server,
  state: "ok",
  reason: "ok",
  fix: null,
});

export const serverLs: ServerLsData = {
  activeProfile: "default",
  servers: [
    { id: "srv-docs", name: "docs-search", transport: "stdio", enabled: true },
    { id: "srv-corp", name: "corp-tools", transport: "http", enabled: true },
    { id: "srv-wiki", name: "wiki-reader", transport: "http", enabled: true },
    { id: "srv-mail", name: "mail-bridge", transport: "stdio", enabled: true },
    { id: "srv-issues", name: "issue-tracker", transport: "http", enabled: true },
    { id: "srv-design", name: "design-files", transport: "http", enabled: true },
    { id: "srv-erp", name: "acme-erp", transport: "stdio", enabled: true },
    { id: "srv-notes", name: "scratch-notes", transport: "stdio", enabled: false },
  ],
};

const member = (id: string) => {
  const found = serverLs.servers.find((server) => server.id === id)!;
  return {
    id,
    name: found.name,
    target: found.transport === "http" ? "https://example.test/mcp" : "node server.js",
  };
};

export const profileLs: ProfileLsData = {
  activeProfile: "default",
  profiles: [
    {
      id: "default",
      name: "Default",
      active: true,
      clients: [],
      servers: [
        "srv-docs",
        "srv-corp",
        "srv-wiki",
        "srv-mail",
        "srv-issues",
        "srv-design",
        "srv-erp",
      ].map(member),
    },
    {
      id: "work",
      name: "Work",
      active: false,
      clients: ["cursor"],
      servers: ["srv-corp", "srv-issues", "srv-wiki"].map(member),
    },
    {
      id: "research",
      name: "Research",
      active: false,
      clients: ["claude-desktop"],
      servers: ["srv-docs", "srv-wiki", "srv-notes"].map(member),
    },
  ],
};

const build = (id: string, state: string, tools: number) => ({ id, state, tools });

export const status: StatusDoc = {
  version: "0.0.0-fixture",
  dataDir: "/fixture/data",
  registry: {
    path: "/fixture/data/registry.json",
    exists: true,
    readable: true,
    error: null,
  },
  serverCount: 8,
  profileCount: 3,
  activeProfile: "default",
  secretsBackend: "encrypted-file",
  directEntries: 1,
  auth: {
    counts: {
      ok: 5,
      expiring: 0,
      needs_reauth: 2,
      revoked: 0,
      misconfigured: 0,
      unreachable: 0,
      unknown: 0,
    },
    servers: [
      okRow("docs-search"),
      okRow("corp-tools"),
      okRow("wiki-reader"),
      okRow("mail-bridge"),
      loginRow("issue-tracker", "HTTP 401 invalid_token"),
      loginRow("design-files", "HTTP 401 Unauthorized"),
    ],
  },
  gateway: {
    present: true,
    path: "/fixture/bin/toolport-gateway",
    build: null,
    builds: [
      {
        building: false,
        pid: 4242,
        role: "daemon",
        servers: [
          build("srv-docs", "connected", 14),
          build("srv-corp", "connected", 28),
          build("srv-wiki", "connected", 31),
          build("srv-mail", "connected", 9),
          build("srv-issues", "failed", 0),
          build("srv-design", "failed", 0),
          build("srv-erp", "failed", 0),
        ],
        serversConnected: 4,
        serversFailed: 3,
        serversTotal: 7,
        startedAtMs: 1_790_000_000_000,
        toolsSoFar: 82,
        updatedAtMs: 1_790_000_100_000,
      },
    ],
  },
};
status.gateway.build = status.gateway.builds[0];

const launcher = (client: string, clientName: string, server: string, name: string) => ({
  client,
  clientName,
  entry: name,
  path: `/fixture/home/.${client}/mcp.json`,
  server,
  serverName: name,
  state: "ok",
});

export const clientLs: ClientLsData = {
  clients: [
    {
      id: "claude-code",
      name: "Claude Code",
      path: "/fixture/home/.claude/.claude.json",
      gateway: "managed",
      managed: true,
      scope: null,
      entries: [],
      launchers: [launcher("claude-code", "Claude Code", "srv-docs", "docs-search")],
    },
    {
      id: "claude-desktop",
      name: "Claude Desktop",
      path: "/fixture/home/Claude/config.json",
      gateway: "managed",
      managed: true,
      scope: "research",
      entries: [],
      launchers: [],
    },
    {
      id: "cursor",
      name: "Cursor",
      path: "/fixture/home/.cursor/mcp.json",
      gateway: "managed",
      managed: true,
      scope: "work",
      entries: ["docs-search", "legacy-lint"],
      launchers: [],
    },
    {
      id: "gemini-cli",
      name: "Gemini CLI",
      path: "/fixture/home/.gemini/settings.json",
      gateway: "absent",
      managed: false,
      scope: null,
      entries: [],
      launchers: [],
    },
  ],
};

export const clientDirectLs: ClientDirectLsData = {
  entries: [launcher("claude-code", "Claude Code", "srv-docs", "docs-search")],
};

const tool = (name: string, description: string) => ({ name, description });

const TOOLS: Record<string, Array<{ name: string; description: string }>> = {
  "srv-docs": [
    tool("search_docs", "Full-text search over the indexed documents."),
    tool("get_page", "Return one page as Markdown."),
    tool("list_spaces", "List the document spaces."),
  ],
  "srv-corp": [
    tool("list_projects", "List the projects the account can see."),
    tool("get_project", "Return one project with its milestones."),
  ],
  "srv-wiki": [
    tool("read_article", "Read a wiki article."),
    tool("search_articles", "Search wiki articles by keyword."),
  ],
  "srv-mail": [tool("list_threads", "List recent mail threads.")],
  "srv-notes": [tool("append_note", "Append a line to the scratch note.")],
};

export const inspectOf = (id: string): InspectData => ({
  profile: null,
  servers: [{ id, tools: TOOLS[id] ?? [] }],
});

export const profileInspectOf = (profile: string, ids: string[]): ProfileInspectData => ({
  profile,
  servers: ids.map((id) => ({ id, tools: TOOLS[id] ?? [] })),
});

export const infoOf = (id: string): ServerInfoData => {
  const server = serverLs.servers.find((entry) => entry.id === id)!;
  const http = server.transport === "http";
  const inProfiles = profileLs.profiles
    .filter((profile) => profile.servers.some((entry) => entry.id === id))
    .map((profile) => profile.id);
  return {
    id,
    name: server.name,
    transport: server.transport,
    command: http ? null : server.name === "acme-erp" ? "acme-erp-mcp" : "node",
    args: http ? [] : server.name === "acme-erp" ? ["--stdio"] : ["server.js", "--quiet"],
    url: http ? `https://example.test/${server.name}/mcp` : null,
    cwd: null,
    source: http ? "catalog" : null,
    env:
      server.name === "acme-erp"
        ? [
            { key: "ERP_URL", secret: false },
            { key: "ERP_API_KEY", secret: true },
          ]
        : server.name === "mail-bridge"
          ? [{ key: "MAIL_TOKEN", secret: true }]
          : [],
    disabledTools: server.name === "docs-search" ? ["list_spaces"] : [],
    declareClientCapabilities: false,
    forwardInstructions: false,
    profiles: inProfiles,
  };
};

export const doctor: DoctorData = {
  healthy: true,
  checks: [
    { name: "dataDir", status: "ok", detail: "/fixture/data is writable" },
    { name: "registry", status: "ok", detail: "8 servers, 3 profiles" },
    { name: "activeProfile", status: "ok", detail: "default" },
    { name: "secretsBackend", status: "ok", detail: "encrypted-file" },
    { name: "gatewayBinary", status: "ok", detail: "/fixture/bin/toolport-gateway" },
    { name: "directEntries", status: "ok", detail: "1 direct launcher entries" },
    {
      name: "skills",
      status: "warn",
      detail:
        "3 of 12 deployed skill files would be rejected by their client and hidden from the model: notes/claude-code (frontmatter), review/claude-code (frontmatter), report/cursor (frontmatter); run toolportctl skills sync",
    },
  ],
};

export const searchOf = (query: string): ServerSearchData => ({
  query,
  total: 2,
  results: [
    {
      name: "docs-index",
      description: "Index and search a folder of Markdown documents.",
      category: "knowledge",
      source: "catalog",
      transport: "stdio",
      command: "npx",
      args: ["-y", "docs-index-mcp"],
      url: null,
      envKeys: ["DOCS_ROOT"],
    },
    {
      name: "docs-cloud",
      description: "Search the documents of a cloud workspace.",
      category: "knowledge",
      source: "catalog",
      transport: "http",
      command: null,
      args: [],
      url: "https://example.test/docs-cloud/mcp",
      envKeys: [],
    },
  ],
});

const entry = (name: string, status: string, target: string) => ({
  name,
  status,
  target,
  transport: "stdio",
});

const importData = (selected: string[], dryRun: boolean): ClientImportData => ({
  client: "cursor",
  name: "Cursor",
  path: "/fixture/home/.cursor/mcp.json",
  dryRun,
  selected: selected.length > 0,
  gateway: ["toolport"],
  direct: [
    entry("legacy-lint", "importable", "node lint-server.js"),
    entry("docs-search", "already", "node server.js --quiet"),
    entry("token-tool", "credential", "node token.js --key <redacted>"),
  ],
  imported: selected.map((name) => ({ id: name, name })),
  skipped: [],
  profile: null,
  secrets: [],
});

export const importPreview = (selected: string[]) => importData(selected, true);

const uninstallData = (dryRun: boolean) => ({
  clients: [
    {
      client: "claude-code",
      path: "/fixture/home/.claude/.claude.json",
      removed: ["acme-erp"],
      backup: dryRun ? null : "/fixture/home/.claude/.claude.json.toolport-bak",
      error: null,
    },
  ],
  dryRun,
  id: "srv-erp",
  name: "acme-erp",
  secretsRemoved: ["ERP_API_KEY"],
});

const editData = (dryRun: boolean, args: { added: string[]; removed: string[] }) => ({
  changed: true,
  dryRun,
  id: "work",
  name: "Work",
  notInProfile: [],
  oldName: "Work",
  renamed: false,
  servers: {
    added: args.added,
    after: ["srv-corp", "srv-issues", "srv-wiki", ...args.added],
    before: ["srv-corp", "srv-issues", "srv-wiki"],
    removed: args.removed,
  },
});

const rmData = (dryRun: boolean) => ({
  clients: [
    {
      client: "cursor",
      name: "Cursor",
      backup: dryRun ? null : "/fixture/home/.cursor/mcp.json.toolport-bak",
      error: null,
    },
  ],
  dryRun,
  id: "work",
  left: [],
  name: "Work",
  servers: 3,
});

const syncData = (dryRun: boolean) => ({
  dryRun,
  clients: [
    {
      client: "claude-code",
      gateway: "managed",
      removed: [],
      kept: [],
      direct: ["docs-search"],
      backups: [],
      error: null,
    },
    {
      client: "cursor",
      gateway: "managed",
      removed: [
        { name: "docs-search", reason: "redundant" },
        { name: "legacy-lint", reason: "orphan" },
      ],
      kept: [],
      direct: [],
      backups: dryRun ? [] : ["/fixture/home/.cursor/mcp.json.toolport-bak"],
      error: null,
    },
  ],
});

const clientEdit = (dryRun: boolean): ClientEditData => ({
  backup: null,
  changed: true,
  client: "gemini-cli",
  dryRun,
  followsActive: null,
  name: "Gemini CLI",
  notInClient: [],
  path: "/fixture/home/.gemini/settings.json",
  profiles: { added: ["Work"], after: ["Work"], before: [], removed: [] },
  scope: { after: "work", before: null },
});

const directAdd = (dryRun: boolean): ClientDirectAddData => ({
  action: "added",
  backup: null,
  changed: true,
  client: "cursor",
  clientName: "Cursor",
  dryRun,
  entry: "docs-search",
  launcher: {
    args: ["direct", "run", "srv-docs"],
    command: "/fixture/bin/toolportctl",
    env: { TOOLPORT_DATA_DIR: "/fixture/data" },
  },
  notes: [],
  path: "/fixture/home/.cursor/mcp.json",
  server: "srv-docs",
  serverName: "docs-search",
  tradeoff:
    "A direct entry bypasses the Toolport gateway: its tools are not covered by profile tool scopes, approvals, receipts or lazy discovery, and every client with a direct entry starts its own process of the server instead of sharing one.",
});

const directRm = (dryRun: boolean): ClientDirectRmData => ({
  action: "removed",
  backup: null,
  changed: true,
  client: "claude-code",
  clientName: "Claude Code",
  dryRun,
  entry: "docs-search",
  notes: [],
  path: "/fixture/home/.claude/.claude.json",
  server: "srv-docs",
  serverName: "docs-search",
});

const skillsSync = (dryRun: boolean) => ({
  backupRoot: "/fixture/home/.backups",
  cleaned: [],
  clientCount: 13,
  clientSource: "default",
  collisions: [],
  dryRun,
  entries: [],
  globalMode: true,
  kept: 0,
  outputRoot: "/fixture/home",
  replaced: 3,
  repo: "/fixture/skills",
  ruleCount: 0,
  skillCount: 12,
  syncedAt: "2026-10-04T12:00:00Z",
  targetedClients: ["claude-code"],
});

const login401 = ctlFailure("inspect_failed", "issue-tracker: HTTP 401 invalid_token");

/** Replies of the dev browser fixture for what the Servers screen runs. */
export const serversCtlFixtures = new Map<string, unknown>([
  ["commands", commandsServed],
  ["status", status],
  ["server ls", serverLs],
  ["profile ls", profileLs],
  ["client ls", clientLs],
  ["client direct ls", clientDirectLs],
  ["doctor", doctor],
  ...serverLs.servers.map((server): [string, unknown] => [
    `server info ${server.id}`,
    infoOf(server.id),
  ]),
  ...serverLs.servers.map((server): [string, unknown] => [
    `inspect ${server.id}`,
    server.id === "srv-issues"
      ? login401
      : server.id === "srv-design"
        ? ctlFailure("inspect_failed", "design-files: HTTP 401 Unauthorized")
        : server.id === "srv-erp"
          ? ctlFailure("inspect_failed", "acme-erp: could not start acme-erp-mcp")
          : inspectOf(server.id),
  ]),
  ["profile inspect default", login401],
  ["profile inspect work", login401],
  [
    "profile inspect research",
    profileInspectOf("research", ["srv-docs", "srv-wiki", "srv-notes"]),
  ],
  ["server search docs --limit 20", searchOf("docs")],
  ["server search docs --limit 20 --offline", searchOf("docs")],
  [
    "server install docs-index",
    { envKeys: ["DOCS_ROOT"], id: "srv-index", name: "docs-index", source: "catalog" },
  ],
  [
    "server new notes-index --command node --arg index.js",
    { id: "srv-notes-index", name: "notes-index" },
  ],
  ["server edit srv-docs --command bun", { changed: ["command"], id: "srv-docs" }],
  ["skills sync --dry-run", skillsSync(true)],
  ["skills sync", skillsSync(false)],
  ["server uninstall srv-erp --dry-run", uninstallData(true)],
  ["server uninstall srv-erp", uninstallData(false)],
  [
    "profile edit work --add-server srv-docs --dry-run",
    editData(true, { added: ["srv-docs"], removed: [] }),
  ],
  [
    "profile edit work --add-server srv-docs",
    editData(false, { added: ["srv-docs"], removed: [] }),
  ],
  ["profile rm work --dry-run", rmData(true)],
  ["profile rm work", rmData(false)],
  [
    "profile create demo --dry-run",
    { created: true, dryRun: true, id: "demo", name: "demo" },
  ],
  ["profile create demo", { created: true, dryRun: false, id: "demo", name: "demo" }],
  ["client sync --dry-run", syncData(true)],
  ["client sync", syncData(false)],
  ["client edit gemini-cli --set-profiles work --dry-run", clientEdit(true)],
  ["client edit gemini-cli --set-profiles work", clientEdit(false)],
  ["client import cursor --dry-run", importPreview([])],
  ["client import cursor --select legacy-lint --dry-run", importPreview(["legacy-lint"])],
  ["client import cursor --select legacy-lint", importData(["legacy-lint"], false)],
  ["client direct add srv-docs --client cursor --dry-run", directAdd(true)],
  ["client direct add srv-docs --client cursor", directAdd(false)],
  ["client direct rm srv-docs --client claude-code --dry-run", directRm(true)],
  ["client direct rm srv-docs --client claude-code", directRm(false)],
]);

export const serversWorld = {
  status,
  serverLs,
  profileLs,
  clientLs,
  clientDirectLs,
  doctor,
};
