use super::*;
use serde_json::{json, Value};
use std::path::Path;

const GOLDEN: &str = "tests/fixtures/ctl/usage-pins.golden";

const CASES: &[&[&str]] = &[
    &[],
    &["--help"],
    &["-h"],
    &["--json"],
    &["--bogus"],
    &["--json", "--bogus", "status"],
    &["--data-dir"],
    &["--data-dir="],
    &["--json", "--data-dir"],
    &["frobnicate"],
    &["--json", "frobnicate"],
    &["status", "extra"],
    &["--json", "status", "extra"],
    &["status", "--bogus"],
    &["--json", "status", "--bogus"],
    &["doctor", "--bogus"],
    &["--json", "doctor", "--bogus"],
    &["doctor", "extra"],
    &["auth", "--bogus"],
    &["--json", "auth", "--bogus"],
    &["auth", "statusline", "--bogus"],
    &["auth", "statusline", "extra"],
    &["auth", "hook", "extra"],
    &["--json", "auth", "hook", "extra"],
    &["auth"],
    &["--json", "auth"],
    &["auth", "nope"],
    &["auth", "probe", "--bogus"],
    &["--json", "auth", "probe", "--bogus"],
    &["auth", "probe", "extra"],
    &["auth", "probe", "--server"],
    &["auth", "probe", "--server="],
    &["auth", "probe", "--force=1"],
    &["auth", "probe", "--server", "nope"],
    &["--json", "auth", "probe", "--server", "nope"],
    &["auth", "login"],
    &["--json", "auth", "login"],
    &["auth", "login", "a", "b"],
    &["auth", "login", "--bogus"],
    &["auth", "login", "--no-open"],
    &["auth", "login", "nope"],
    &["--json", "auth", "login", "nope"],
    &["status", "--", "x"],
    &["server", "ls", "--bogus"],
    &["server", "ls", "extra"],
    &["server", "ls", "--"],
    &["--json", "server", "ls", "extra"],
    &["server"],
    &["--json", "server"],
    &["server", "add"],
    &["server", "--bogus"],
    &["server", "--"],
    &["server", "search", "--bogus"],
    &["server", "search", "--limit"],
    &["server", "search", "--limit", "abc"],
    &["server", "search", "--limit=3"],
    &["server", "search", "--offline=1"],
    &["server", "search", "--offline", "--limit", "x1"],
    &["server", "install"],
    &["server", "install", "a", "b"],
    &["server", "install", "--bogus"],
    &["server", "install", "--offline"],
    &["server", "install", "-x"],
    &["server", "install", "nope", "--offline"],
    &["--json", "server", "install", "nope", "--offline"],
    &["server", "uninstall"],
    &["server", "uninstall", "--bogus"],
    &["server", "uninstall", "a", "--dry-run=1"],
    &["server", "uninstall", "--keep-clients"],
    &["server", "uninstall", "nope", "--dry-run"],
    &["--json", "server", "uninstall", "nope"],
    &["server", "info"],
    &["server", "info", "a", "b"],
    &["server", "info", "--bogus"],
    &["server", "info", "nope"],
    &["--json", "server", "info", "nope"],
    &["server", "new"],
    &["server", "new", "a"],
    &["server", "new", "a", "--command"],
    &["server", "new", "a", "--url"],
    &["server", "new", "a", "--bogus"],
    &["server", "new", "a", "b", "--command", "x"],
    &["server", "new", "--command", "x"],
    &["server", "new", "a", "--name", "b", "--command", "x"],
    &["server", "new", "alpha", "--command", "x"],
    &["--json", "server", "new", "alpha", "--command", "x"],
    &["server", "edit"],
    &["server", "edit", "a"],
    &["server", "edit", "a", "--name"],
    &["server", "edit", "a", "--arg"],
    &["server", "edit", "a", "--bogus"],
    &["server", "edit", "a", "b", "--name", "c"],
    &["server", "edit", "nope", "--name", "x"],
    &["--json", "server", "edit", "nope", "--name", "x"],
    &["inspect"],
    &["inspect", "a", "b"],
    &["inspect", "--bogus"],
    &["--json", "inspect", "--bogus"],
    &["inspect", "-"],
    &["inspect", "nope"],
    &["--json", "inspect", "nope"],
    &["profile"],
    &["--json", "profile"],
    &["profile", "--bogus"],
    &["profile", "inspect", "a", "b"],
    &["profile", "inspect", "--bogus"],
    &["profile", "inspect", "nope"],
    &["--json", "profile", "inspect", "nope"],
    &["profile", "ls"],
    &["--json", "profile", "ls"],
    &["profile", "ls", "-v"],
    &["profile", "ls", "--bogus"],
    &["profile", "ls", "extra"],
    &["profile", "ls", "--verbose=1"],
    &["profile", "create"],
    &["profile", "create", "a", "b"],
    &["profile", "create", "--bogus"],
    &["profile", "create", " "],
    &["profile", "create", "x", "--force=1"],
    &["profile", "create", "x", "--dry-run=1"],
    &["profile", "create", "Demo", "--dry-run"],
    &["--json", "profile", "create", "Demo", "--dry-run"],
    &["profile", "create", "work"],
    &["--json", "profile", "create", "work"],
    &["profile", "edit"],
    &["profile", "edit", "a", "b"],
    &["profile", "edit", "a", "--bogus"],
    &["profile", "edit", "a", "--name"],
    &["profile", "edit", "a", "--servers"],
    &["profile", "edit", "work", "--servers", "x", "--add-server", "y"],
    &["--json", "profile", "edit", "work", "--servers", "x", "--add-server", "y"],
    &["profile", "edit", "work", "--name", ""],
    &["profile", "edit", "nope", "--name", "x"],
    &["--json", "profile", "edit", "nope", "--name", "x"],
    &["profile", "edit", "work", "--add-server", "ghost"],
    &["profile", "edit", "work", "--name", "default"],
    &["profile", "edit", "work"],
    &["profile", "edit", "work", "--remove-server", "beta"],
    &["profile", "edit", "work", "--name", "Job", "--add-server", "alpha", "--dry-run"],
    &["--json", "profile", "edit", "work", "--set-servers", "alpha,beta", "--dry-run"],
    &["profile", "rm"],
    &["profile", "rm", "a", "b"],
    &["profile", "rm", "--bogus"],
    &["profile", "rm", "a", "--no-clients=1"],
    &["profile", "rm", "a", "--force=1"],
    &["profile", "rm", "nope", "--dry-run"],
    &["profile", "rm", "nope", "-f"],
    &["--json", "profile", "rm", "nope"],
    &["profile", "rm", "work", "--dry-run"],
    &["--json", "profile", "rm", "default", "--dry-run", "--no-clients"],
    &["client"],
    &["--json", "client"],
    &["client", "--bogus"],
    &["client", "ls", "--bogus"],
    &["client", "ls", "extra"],
    &["client", "sync", "--bogus"],
    &["client", "sync", "extra"],
    &["client", "sync", "--client"],
    &["client", "sync", "--client", "x", "--bogus"],
    &["client", "sync", "--dry-run=1"],
    &["client", "sync", "--client=x"],
    &["--json", "client", "sync", "--bogus"],
    &["client", "edit"],
    &["client", "edit", "a", "b"],
    &["client", "edit", "x", "--bogus"],
    &["client", "edit", "x", "--add-profile"],
    &["client", "edit", "x", "--force=1"],
    &["client", "edit", "x", "--add-profile", "a", "--remove-profile", "b"],
    &["--json", "client", "edit", "x", "--add-profile", "a", "--set-profiles", "b"],
    &["client", "edit", "x", "--add-server", "s"],
    &["client", "edit", "x", "-e"],
    &["client", "edit", "x", "--file", "f"],
    &["client", "import"],
    &["client", "import", "a", "b"],
    &["client", "import", "x", "--bogus"],
    &["client", "import", "x", "--select"],
    &["client", "import", "x", "--all=1"],
    &["client", "import", "x", "--all", "--select", "a"],
    &["client", "import", "x", "--select", ","],
    &["secret"],
    &["--json", "secret"],
    &["secret", "ls"],
    &["secret", "--bogus"],
    &["secret", "set"],
    &["secret", "set", "a"],
    &["secret", "set", "a", "b", "c"],
    &["secret", "set", "--bogus"],
    &["secret", "set", "a", "b", "--value-env"],
    &["secret", "set", "a", "b", "--reveal"],
    &["secret", "set", "a", "b", "--value-env=X"],
    &["secret", "set", "nope", "KEY"],
    &["--json", "secret", "set", "nope", "KEY"],
    &["secret", "set", "alpha", "a::b"],
    &["secret", "set", "alpha", "__x__"],
    &["secret", "get"],
    &["secret", "get", "a"],
    &["secret", "get", "a", "b", "--reveal=1"],
    &["secret", "get", "a", "b", "--bogus"],
    &["secret", "get", "a", "b", "--value-env", "X"],
    &["secret", "get", "alpha", ""],
    &["secret", "rm"],
    &["secret", "rm", "a"],
    &["secret", "rm", "a", "b", "--bogus"],
    &["secret", "rm", "a", "b", "--reveal"],
    &["secret", "rm", "alpha", "a::b"],
    &["context"],
    &["--json", "context"],
    &["context", "nope"],
    &["context", "loads", "--bogus"],
    &["context", "loads", "--bogus=1"],
    &["context", "loads", "--profile"],
    &["context", "loads", "--cwd"],
    &["context", "loads", "extra"],
    &["context", "loads", "foo=bar"],
    &["context", "loads", "--profile", "x", "--bogus"],
    &["--json", "context", "loads", "--bogus"],
    &["context", "checkpoint-status", "--bogus"],
    &["context", "checkpoint-status", "--profile"],
    &["context", "checkpoint-status", "--window"],
    &["context", "checkpoint-status", "--window", "abc"],
    &["context", "checkpoint-status", "--window=abc"],
    &["context", "checkpoint-status", "--checkpoint-at", "x"],
    &["context", "checkpoint-status", "--window", "abc", "--bogus"],
    &["context", "checkpoint-status", "--bogus", "--window", "abc"],
    &["context", "checkpoint-status", "--window", "--bogus"],
    &["context", "checkpoint-status", "extra"],
    &["context", "checkpoint-status", "--window=1=2"],
    &["context", "plan", "--bogus"],
    &["context", "plan", "--dry-run"],
    &["context", "plan", "--home"],
    &["context", "plan", "--rules=1"],
    &["context", "plan", "--no-persist=1"],
    &["context", "plan", "extra"],
    &["context", "plan", "--home", "/x", "--bogus"],
    &["context", "apply", "--bogus"],
    &["context", "apply", "--home"],
    &["context", "apply", "--rules=1"],
    &["context", "apply", "--dry-run=1"],
    &["context", "apply", "extra"],
    &["context", "sync", "--bogus"],
    &["context", "sync", "--no-persist=1"],
    &["context", "sync", "--dry-run=1"],
    &["context", "sync", "extra"],
    &["--json", "context", "plan", "--bogus"],
    &["context", "folders", "--bogus"],
    &["context", "folders", "--cwd"],
    &["context", "folders", "--enable=1"],
    &["context", "folders", "--disable=1"],
    &["context", "folders", "--enable", "--disable"],
    &["context", "folders", "extra"],
    &["context", "folders", "--cwd", "/x", "--bogus"],
    &["context", "folders", "--bogus", "--cwd"],
    &["--json", "context", "folders", "--enable", "--disable"],
    &["context", "init", "extra"],
    &["context", "init", "--bogus"],
    &["context", "init", "--home"],
    &["context", "init", "--yes=1"],
    &["context", "init", "--dry-run=1"],
    &["--json", "context", "init", "--bogus"],
    &["context", "status", "extra"],
    &["context", "status", "--bogus"],
    &["context", "status", "--home"],
    &["context", "status", "--dry-run"],
    &["context", "client"],
    &["--json", "context", "client"],
    &["context", "client", "nope"],
    &["context", "client", "add"],
    &["context", "client", "add", "--glob"],
    &["context", "client", "add", "acme", "extra"],
    &["context", "client", "add", "acme", "--bogus"],
    &["context", "client", "add", "acme", "--dry-run=1"],
    &["context", "client", "add", "acme", "--glob"],
    &["context", "client", "add", "a\nb"],
    &["context", "client", "add", "a---b"],
    &["context", "client", "add", "acme", "--glob", "x\n---\ny"],
    &["context", "client", "add", " "],
    &["--json", "context", "client", "add", "a\nb"],
    &["context", "client", "list", "extra"],
    &["context", "client", "list", "--bogus"],
    &["context", "client", "list", "--home"],
    &["context", "profile"],
    &["--json", "context", "profile"],
    &["context", "profile", "nope"],
    &["context", "profile", "add"],
    &["context", "profile", "add", "a", "b"],
    &["context", "profile", "add", "Bad Name"],
    &["context", "profile", "add", "../x"],
    &["context", "profile", "add", "ok", "--org-mode", "weird"],
    &["context", "profile", "add", "ok", "--org-mode"],
    &["context", "profile", "add", "ok", "--rules"],
    &["context", "profile", "add", "ok", "--servers"],
    &["context", "profile", "add", "ok", "--no-org=1"],
    &["context", "profile", "add", "ok", "--bogus"],
    &["--json", "context", "profile", "add", "Bad Name"],
    &["context", "profile", "list", "extra"],
    &["context", "profile", "list", "--bogus"],
    &["context", "profile", "remove"],
    &["context", "profile", "remove", "a", "b"],
    &["context", "profile", "remove", "../x", "--purge"],
    &["context", "profile", "remove", "a/b", "--purge"],
    &["context", "profile", "remove", "x", "--purge=1"],
    &["context", "profile", "remove", "x", "--bogus"],
    &["--json", "context", "profile", "remove", "..", "--purge"],
    &["context", "disable", "extra"],
    &["context", "disable", "--bogus"],
    &["context", "disable", "--purge-profiles=1"],
    &["context", "disable", "--home"],
    &["compression"],
    &["--json", "compression"],
    &["compression", "enable", "--bogus"],
    &["compression", "enable", "extra"],
    &["compression", "enable", "--port"],
    &["compression", "enable", "--port", "x"],
    &["compression", "enable", "--provider", "x"],
    &["compression", "enable", "--mode", "x"],
    &["compression", "enable", "--telemetry", "x"],
    &["compression", "enable", "--dry-run=1"],
    &["--json", "compression", "enable", "--bogus"],
    &["compression", "disable", "--bogus"],
    &["compression", "disable", "extra"],
    &["compression", "disable", "--teardown=1"],
    &["compression", "set-provider"],
    &["compression", "set-provider", "x"],
    &["compression", "set-provider", "none", "extra"],
    &["compression", "set-provider", "--bogus"],
    &["--json", "compression", "set-provider"],
    &["compression", "use"],
    &["compression", "use", "a", "b"],
    &["compression", "use", "--bogus"],
    &["compression", "sync", "--bogus"],
    &["compression", "sync", "--mcpm-root"],
    &["compression", "sync", "extra"],
    &["compression", "pin", "a", "b"],
    &["compression", "pin", "--bogus"],
    &["compression", "pin", "--install=1"],
    &["compression", "seal", "a", "b"],
    &["compression", "seal", "--bogus"],
    &["compression", "env", "--cwd"],
    &["compression", "env", "extra"],
    &["compression", "doctor", "extra"],
    &["compression", "presets", "--bogus"],
    &["compression", "presets", "--refresh=1"],
    &["compression", "--bogus"],
    &["compression", "status", "--bogus"],
    &["compression", "status", "extra"],
    &["compression", "presets", "extra"],
    &["compression", "verify", "--bogus"],
    &["compression", "verify", "--limit"],
    &["compression", "verify", "--limit", "abc"],
    &["compression", "verify", "--limit=abc"],
    &["compression", "verify", "--limit", "abc", "extra"],
    &["compression", "verify", "--min-turns", "x"],
    &["compression", "verify", "--transcripts"],
    &["compression", "verify", "extra"],
    &["compression", "verify", "-x"],
    &["compression", "verify", "--by-pin=1"],
    &["compression", "verify", "--bogus=1"],
    &["compression", "verify", "--"],
    &["compression", "verify", "--limit", "1", "--bogus"],
    &["--json", "compression", "verify", "--bogus"],
    &["compression", "ledger", "--bogus"],
    &["compression", "ledger", "extra"],
    &["compression", "ledger", "summary", "--bogus"],
    &["compression", "ledger", "summary", "--provider"],
    &["compression", "ledger", "summary", "--since", "bogus"],
    &["compression", "ledger", "summary", "extra"],
    &["compression", "ledger", "record"],
    &["compression", "ledger", "record", "--bogus"],
    &["compression", "ledger", "record", "--provider"],
    &["compression", "ledger", "record", "--provider", "bogus"],
    &["compression", "ledger", "record", "--provider", "none"],
    &[
        "compression",
        "ledger",
        "record",
        "--provider",
        "none",
        "--before",
        "x",
    ],
    &[
        "compression",
        "ledger",
        "record",
        "--provider",
        "none",
        "--before",
        "1",
    ],
    &[
        "compression",
        "ledger",
        "record",
        "--provider",
        "none",
        "--after",
        "1",
    ],
    &[
        "compression",
        "ledger",
        "record",
        "--provider",
        "none",
        "--before",
        "1",
        "--after",
        "x",
    ],
    &["compression", "ledger", "record", "extra"],
    &["--json", "compression", "ledger", "record"],
    &["compression", "proxy"],
    &["compression", "proxy", "sideways"],
    &["compression", "proxy", "up", "extra"],
    &["--json", "compression", "proxy"],
    &["compression", "update", "--bogus"],
    &["compression", "update", "--to"],
    &["compression", "update", "--latest=1"],
    &["compression", "update", "extra"],
    &["compression", "update", "--latest", "--bogus"],
    &["import"],
    &["--json", "import"],
    &["import", "--bogus"],
    &["import", "nope"],
    &["import", "mcpm"],
    &["import", "mcpm", "a", "b"],
    &["import", "mcpm", "--bogus"],
    &["import", "mcpm", "-"],
    &["import", "mcpm", "a", "--tools"],
    &["import", "mcpm", "a", "--home"],
    &["import", "mcpm", "a", "--short-ids"],
    &["import", "mcpm", "a", "--name-map"],
    &["import", "mcpm", "a", "--dry-run=1"],
    &["import", "mcpm", "--dry-run"],
    &["import", "mcpm", "a", "--tools=t"],
    &["--json", "import", "mcpm"],
    &["import", "rename-refs"],
    &["import", "rename-refs", "a"],
    &["import", "rename-refs", "a", "b"],
    &["import", "rename-refs", "a", "--bogus"],
    &["import", "rename-refs", "a", "--tools"],
    &["import", "rename-refs", "a", "--tools", "t"],
    &["import", "rename-refs", "a", "--tools", "t", "--paths"],
    &[
        "import",
        "rename-refs",
        "a",
        "--tools",
        "t",
        "--paths",
        "--dry-run",
    ],
    &["import", "rename-refs", "--paths", "x"],
    &["import", "rename-refs", "a", "--paths", "x"],
    &["import", "rename-refs", "a", "--paths", "x", "y", "--bogus"],
    &[
        "import",
        "rename-refs",
        "a",
        "--paths",
        "x",
        "--paths",
        "--bogus",
    ],
    &["import", "rename-refs", "a", "--home"],
    &["import", "rename-refs", "a", "--short-ids"],
    &["mcp"],
    &["--json", "mcp"],
    &["mcp", "serve"],
    &["mcp", "--bogus"],
    &["mcp", "install", "--bogus"],
    &["mcp", "install", "extra"],
    &["mcp", "install", "-"],
    &["mcp", "install", "-x"],
    &["mcp", "install", "--profile"],
    &["mcp", "install", "--profile=x"],
    &["mcp", "install", "--profile", "p", "extra"],
    &["mcp", "install", "--bogus", "--profile"],
    &["mcp", "install", "--profile", "--bogus"],
    &["--json", "mcp", "install", "--profile"],
    &["mcp", "uninstall", "extra"],
    &["mcp", "uninstall", "--bogus"],
    &["mcp", "doctor", "extra"],
    &["mcp", "doctor", "-"],
    &["mcp", "tools", "extra"],
    &["--json", "mcp", "tools", "extra"],
    &["usage", "--bogus"],
    &["usage", "extra"],
    &["usage", "-"],
    &["usage", "-x"],
    &["usage", "--root"],
    &["usage", "--root="],
    &["usage", "--root=", "--bogus"],
    &["usage", "--bogus", "--root="],
    &["usage", "--no-refresh=1"],
    &["usage", "--no-refresh", "--bogus"],
    &["usage", "--root", "d", "extra"],
    &["usage", "--root=d", "extra"],
    &["usage", "--root=d=e", "--bogus=1"],
    &["--json", "usage", "--bogus"],
    &["--json", "usage", "--root"],
    &["council"],
    &["--json", "council"],
    &["council", "nope"],
    &["council", "--bogus"],
    &["council", "install", "--bogus"],
    &["council", "install", "extra"],
    &["council", "install", "--api-key-env"],
    &["council", "install", "--api-key-env", "CTL_PIN_UNSET_VAR"],
    &[
        "--json",
        "council",
        "install",
        "--api-key-env",
        "CTL_PIN_UNSET_VAR",
    ],
    &["council", "install", "--api-key-env=X"],
    &["council", "uninstall", "--bogus"],
    &["council", "uninstall", "extra"],
    &["council", "doctor", "extra"],
    &["council", "doctor", "--bogus"],
    &["council", "tools", "extra"],
    &["--json", "council", "tools", "--bogus"],
    &["skills"],
    &["--json", "skills"],
    &["skills", "nope"],
    &["skills", "--bogus"],
    &["skills", "sync", "--bogus"],
    &["skills", "sync", "--repo"],
    &["skills", "sync", "--home"],
    &["skills", "sync", "--client"],
    &["skills", "sync", "--project=1"],
    &["skills", "sync", "--dry-run=1"],
    &["skills", "sync", "--bogus=1"],
    &["skills", "sync", "extra"],
    &["skills", "sync", "foo=bar"],
    &["skills", "sync", "-"],
    &["skills", "sync", "--global", "--project"],
    &["skills", "sync", "--repo=", "--bogus"],
    &["skills", "sync", "--path", "x"],
    &["--json", "skills", "sync", "--bogus"],
    &["skills", "ls", "--bogus"],
    &["skills", "ls", "--client", "x"],
    &["skills", "ls", "--repo"],
    &["skills", "ls", "extra"],
    &["skills", "lint", "--bogus"],
    &["skills", "lint", "--name"],
    &["skills", "lint", "--name=x", "--bogus"],
    &["skills", "lint", "extra"],
    &["skills", "diff", "--bogus"],
    &["skills", "diff", "--project"],
    &["skills", "diff", "--dry-run"],
    &["skills", "diff", "--home"],
    &["skills", "init", "--bogus"],
    &["skills", "init", "extra"],
    &["skills", "init", "--path"],
    &["skills", "init", "--repo"],
    &["skills", "init", "--name"],
    &["skills", "init", "--dry-run=1"],
    &["skills", "init", "--bogus=1"],
    &["skills", "init", "-"],
    &["--json", "skills", "init", "--bogus"],
    &["skills", "add"],
    &["skills", "add", "a", "b"],
    &["skills", "add", "--type"],
    &["skills", "add", "a", "--bogus"],
    &["skills", "add", "a", "--with-progressive=1"],
    &["skills", "add", "--dry-run"],
    &["skills", "audit", "extra"],
    &["skills", "audit", "--bogus"],
    &["skills", "audit", "--path"],
    &["skills", "audit", "--dry-run"],
    &["skills", "bundle", "extra"],
    &["skills", "bundle", "--bogus"],
    &["skills", "bundle", "--output"],
    &["skills", "bundle", "--skills"],
    &["skills", "bundle", "--dry-run=1"],
    &["skills", "unbundle"],
    &["skills", "unbundle", "a", "b"],
    &["skills", "unbundle", "--path"],
    &["skills", "unbundle", "a", "--bogus"],
    &["skills", "unbundle", "--dry-run"],
    &["--json", "skills", "unbundle"],
    &["skills", "status", "--bogus"],
    &["skills", "status", "extra"],
    &["skills", "status", "--strict=1"],
    &["skills", "status", "--client"],
    &["skills", "status", "--home"],
    &["skills", "status", "--repo"],
    &["skills", "status", "--project"],
    &["skills", "clean", "--bogus"],
    &["skills", "clean", "extra"],
    &["skills", "clean", "--client"],
    &["skills", "clean", "--dry-run=1"],
    &["skills", "clean", "--global", "--project"],
    &["--json", "skills", "clean", "--global", "--project"],
    &["skills", "uninstall"],
    &["skills", "uninstall", "a", "b"],
    &["skills", "uninstall", "a", "--bogus"],
    &["skills", "uninstall", "a", "--global", "--project"],
    &["skills", "uninstall", "a", "--client", "x"],
    &["skills", "uninstall", "--repo"],
    &["skills", "resolve", "--bogus"],
    &["skills", "resolve", "extra"],
    &["skills", "resolve", "--migrate", "--no-migrate"],
    &["skills", "resolve", "--global", "--project"],
    &["skills", "resolve", "--migrate=1"],
    &["skills", "resolve", "--client"],
    &["skills", "tap"],
    &["--json", "skills", "tap"],
    &["skills", "tap", "nope"],
    &["skills", "tap", "add"],
    &["skills", "tap", "add", "a/b", "c/d"],
    &["skills", "tap", "add", "a/b", "--name"],
    &["skills", "tap", "add", "a/b", "--bogus"],
    &["skills", "tap", "add", "a/b", "--dry-run=1"],
    &["skills", "tap", "ls", "extra"],
    &["skills", "tap", "ls", "--bogus"],
    &["skills", "tap", "remove"],
    &["skills", "tap", "remove", "a", "b"],
    &["skills", "tap", "remove", "a", "--bogus"],
    &["skills", "tap", "update", "a", "b"],
    &["skills", "tap", "update", "--bogus"],
    &["skills", "search"],
    &["skills", "search", "a", "b"],
    &["skills", "search", "--bogus"],
    &["skills", "install"],
    &["skills", "install", "a", "b"],
    &["skills", "install", "a", "--bogus"],
    &["skills", "install", "a", "--path"],
    &["skills", "install", "a", "--no-audit=1"],
    &["--json", "skills", "install"],
    &["agents"],
    &["--json", "agents"],
    &["agents", "nope"],
    &["agents", "--bogus"],
    &["agents", "ls", "--bogus"],
    &["agents", "ls", "extra"],
    &["agents", "ls", "--path"],
    &["agents", "ls", "--repo"],
    &["agents", "ls", "--project"],
    &["agents", "ls", "--dry-run"],
    &["agents", "lint", "--bogus"],
    &["agents", "lint", "extra"],
    &["agents", "lint", "--path"],
    &["agents", "lint", "--strict"],
    &["agents", "audit", "--bogus"],
    &["agents", "audit", "extra"],
    &["agents", "audit", "--path"],
    &["agents", "diff", "--bogus"],
    &["agents", "diff", "extra"],
    &["agents", "diff", "--home"],
    &["agents", "status", "--bogus"],
    &["agents", "status", "extra"],
    &["agents", "status", "--strict=1"],
    &["agents", "status", "--home"],
    &["agents", "status", "--project"],
    &["agents", "status", "--client", "x"],
    &["agents", "add"],
    &["agents", "add", "a", "b"],
    &["agents", "add", "a", "--bogus"],
    &["agents", "add", "a", "--path"],
    &["agents", "add", "a", "--dry-run=1"],
    &["agents", "add", "--dry-run"],
    &["--json", "agents", "add"],
    &["agents", "clean", "--bogus"],
    &["agents", "clean", "extra"],
    &["agents", "clean", "--client"],
    &["agents", "clean", "--dry-run=1"],
    &["agents", "clean", "--global", "--project"],
    &["--json", "agents", "clean", "--global", "--project"],
    &["agents", "uninstall"],
    &["agents", "uninstall", "a", "b"],
    &["agents", "uninstall", "a", "--bogus"],
    &["agents", "uninstall", "a", "--global", "--project"],
    &["agents", "uninstall", "a", "--client", "x"],
    &["agents", "uninstall", "--path"],
    &["agents", "sync", "--bogus"],
    &["agents", "sync", "extra"],
    &["agents", "sync", "--client"],
    &["agents", "sync", "--home"],
    &["agents", "sync", "--project=1"],
    &["agents", "sync", "--global", "--project"],
    &["--json", "agents", "sync", "--bogus"],
    &["styles"],
    &["--json", "styles"],
    &["styles", "nope"],
    &["styles", "--bogus"],
    &["styles", "ls", "--bogus"],
    &["styles", "ls", "extra"],
    &["styles", "ls", "--path"],
    &["styles", "ls", "--repo"],
    &["styles", "ls", "--project"],
    &["styles", "ls", "--dry-run"],
    &["styles", "lint", "--bogus"],
    &["styles", "lint", "extra"],
    &["styles", "lint", "--path"],
    &["styles", "diff", "--bogus"],
    &["styles", "diff", "extra"],
    &["styles", "diff", "--home"],
    &["styles", "status", "--bogus"],
    &["styles", "status", "extra"],
    &["styles", "status", "--home"],
    &["styles", "status", "--project"],
    &["styles", "add"],
    &["styles", "add", "a", "b"],
    &["styles", "add", "a", "--bogus"],
    &["styles", "add", "a", "--path"],
    &["styles", "add", "a", "--dry-run=1"],
    &["styles", "add", "--dry-run"],
    &["--json", "styles", "add"],
    &["styles", "sync", "--bogus"],
    &["styles", "sync", "extra"],
    &["styles", "sync", "--client"],
    &["styles", "sync", "--home"],
    &["styles", "sync", "--project=1"],
    &["styles", "sync", "--global", "--project"],
    &["--json", "styles", "sync", "--bogus"],
    &["styles", "apply"],
    &["styles", "apply", "a", "b"],
    &["styles", "apply", "a", "--bogus"],
    &["styles", "apply", "a", "--client"],
    &["styles", "apply", "a", "--global", "--project"],
    &["styles", "apply", "--dry-run"],
    &["--json", "styles", "apply"],
    &["styles", "remove", "--bogus"],
    &["styles", "remove", "extra"],
    &["styles", "remove", "--client"],
    &["styles", "remove", "--global", "--project"],
    &["styles", "remove", "--dry-run=1"],
    &["styles", "clean", "--bogus"],
    &["styles", "clean", "extra"],
    &["styles", "clean", "--client", "x"],
    &["styles", "clean", "--dry-run=1"],
    &["styles", "clean", "--global", "--project"],
    &["--json", "styles", "clean", "--global", "--project"],
    &["sync"],
    &["--json", "sync"],
    &["sync", "nope"],
    &["sync", "--bogus"],
    &["sync", "push", "--bogus"],
    &["sync", "push", "-"],
    &["sync", "push", "extra"],
    &["sync", "push", "--dry-run=1"],
    &["sync", "push", "--force"],
    &["sync", "pull", "--bogus"],
    &["sync", "pull", "extra"],
    &["sync", "diff", "extra"],
    &["sync", "status", "--bogus"],
    &["sync", "reset", "extra"],
    &["sync", "init"],
    &["--json", "sync", "init"],
    &["sync", "init", "--repo"],
    &["sync", "init", "--branch"],
    &["sync", "init", "--machine-id"],
    &["sync", "init", "--repo", "r"],
    &["sync", "init", "--reconfigure=1"],
    &["sync", "init", "--passphrase-env"],
    &["sync", "init", "--passphrase-env", "CTL_PIN_UNSET_VAR"],
    &[
        "--json",
        "sync",
        "init",
        "--passphrase-env",
        "CTL_PIN_UNSET_VAR",
    ],
    &[
        "sync",
        "init",
        "--passphrase-env",
        "CTL_PIN_UNSET_VAR",
        "--bogus",
    ],
    &[
        "sync",
        "init",
        "--bogus",
        "--passphrase-env",
        "CTL_PIN_UNSET_VAR",
    ],
    &["sync", "rotate-passphrase"],
    &["sync", "rotate-passphrase", "extra"],
    &["sync", "add-project"],
    &["sync", "add-project", "x"],
    &["sync", "add-project", "x", "--name"],
    &["sync", "add-project", "x", "--files"],
    &["sync", "add-project", "a", "b", "--name", "n"],
    &["sync", "add-project", "a", "b", "--bogus"],
    &["sync", "add-project", "x", "--name", "n", "--bogus"],
    &["sync", "remove-project"],
    &["sync", "remove-project", "a", "b"],
    &["sync", "git-sync", "--bogus"],
    &["sync", "git-sync", "--repo"],
    &["sync", "git-sync", "--branch"],
    &["sync", "git-sync", "extra"],
    &["sync", "migrate"],
    &["sync", "migrate", "a", "b"],
    &["sync", "migrate", "d"],
    &["sync", "migrate", "--bogus"],
    &["cc"],
    &["--json", "cc"],
    &["cc", "nope"],
    &["cc", "nope", "--bogus"],
    &["cc", "list", "--bogus"],
    &["cc", "list", "-"],
    &["cc", "list", "a", "b"],
    &["cc", "list", "--marketplace"],
    &["cc", "list", "-m"],
    &["cc", "update", "--dry-run=1"],
    &["cc", "update", "--marketplace=x"],
    &["cc", "update", "-c=1"],
    &["cc", "--bogus"],
    &["--json", "cc", "list", "--bogus"],
    &["update", "--bogus"],
    &["update", "-"],
    &["update", "-x"],
    &["update", "a", "b"],
    &["update", "a", "b", "--bogus"],
    &["update", "--repo"],
    &["update", "--check", "--apply"],
    &["update", "--apply", "--init"],
    &["update", "-c", "--init"],
    &["update", "--check", "--init", "--apply"],
    &["update", "--check=1"],
    &["update", "--repo=x"],
    &["--json", "update", "--bogus"],
    &["--json", "update", "--check", "--apply"],
    &["obs"],
    &["--json", "obs"],
    &["obs", "nope"],
    &["obs", "--bogus"],
    &["obs", "otel"],
    &["--json", "obs", "otel"],
    &["obs", "otel", "nope"],
    &["obs", "otel", "enable", "--bogus"],
    &["obs", "otel", "enable", "extra"],
    &["obs", "otel", "enable", "--port"],
    &["obs", "otel", "enable", "--port="],
    &["obs", "otel", "enable", "--port", "0"],
    &["obs", "otel", "enable", "--port", "70000"],
    &["obs", "otel", "enable", "--port=abc"],
    &["obs", "otel", "enable", "--home"],
    &["obs", "otel", "enable", "--dry-run=1"],
    &["--json", "obs", "otel", "enable", "--port", "0"],
    &["obs", "otel", "disable", "--bogus"],
    &["obs", "otel", "disable", "--port", "4318"],
    &["obs", "otel", "disable", "extra"],
    &["obs", "otel", "status", "--bogus"],
    &["obs", "otel", "status", "--dry-run"],
    &["obs", "otel", "status", "extra"],
    &["--json", "obs", "otel", "status", "--bogus"],
];

fn sample_registry() -> Value {
    json!({
        "version": 1,
        "servers": [
            {"id": "srv-alpha", "name": "alpha", "transport": "stdio", "command": "alpha-mcp", "args": []},
            {"id": "srv-beta", "name": "beta", "transport": "http", "url": "https://example.invalid/mcp"}
        ],
        "profiles": [
            {"id": "default", "name": "Default", "enabledServerIds": ["srv-alpha"]},
            {"id": "work", "name": "Work", "enabledServerIds": []}
        ],
        "activeProfileId": "default"
    })
}

fn render(case: &[&str], dir: &Path) -> String {
    let list: Vec<String> = case.iter().map(|s| s.to_string()).collect();
    let (mut out, mut err) = (Vec::new(), Vec::new());
    let code = run_with(&list, &mut out, &mut err);
    let scrub = |bytes: Vec<u8>| {
        let text = String::from_utf8(bytes).unwrap();
        assert!(
            text.is_empty() || text.ends_with('\n'),
            "{case:?}: {text:?}"
        );
        text.replace(&*dir.to_string_lossy(), "<DATA_DIR>")
    };
    format!(
        "=== {}\nexit {code}\n--- stdout\n{}--- stderr\n{}",
        json!(case),
        scrub(out),
        scrub(err)
    )
}

fn blocks(text: &str) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for line in text.split_inclusive('\n') {
        if line.starts_with("=== ") {
            out.push(String::new());
        }
        out.last_mut()
            .expect("the golden starts with a case header")
            .push_str(line);
    }
    out
}

#[test]
fn usage_and_error_text_of_every_command_is_pinned() {
    let fx = crate::plus::testutil::DataDirFx::new("toolportctl", "pins");
    fx.write_registry(&sample_registry());
    let actual: Vec<String> = CASES.iter().map(|case| render(case, &fx.dir)).collect();
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(GOLDEN);
    if std::env::var_os("UPDATE_GOLDEN").is_some() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, actual.concat()).unwrap();
    }
    let expected = blocks(&std::fs::read_to_string(&path).unwrap());
    assert_eq!(
        actual.len(),
        expected.len(),
        "case count differs from the golden"
    );
    for (got, want) in actual.iter().zip(&expected) {
        assert_eq!(got, want);
    }
}
